### ISSUE TITLE
Understand how to create a Square storefront.

### ISSUE THREAD

**Issue by srjchsv** [rtp-gcp/gcp_icy_bridge#4]
Understand how to create a Square storefront.
* Add a entry to list a item for sale
* Add a capability to order a item
* Understand how to specify payment option using [Gpay](https://developer.squareup.com/reference/square/objects/AcceptedPaymentMethods)

**Comment by netskink** [comment]
In progress.
Can add item to library.  
Can add image to item.

Currently have to add items manually to storefront.
